table_tennis/config/routes.rb
TableTennis::Application.routes.draw do

  get "log_out" => "sessions#destroy", :as => "log_out"
  match 'history/:id', :controller => 'matches', :action => 'history'
  match 'decisions/:id', :controller => 'matches', :action => 'decision'
  match 'results/:id', :controller => 'matches', :action => 'result'
  match 'challenges/:id', :controller => 'matches', :action => 'challenge'
  match 'newOne/:id', :controller => 'matches', :action => 'new'
  match 'list/:id', :controller => 'users', :action => 'index'
  resources :matches
  resources :users
  resources :sessions, only: [:new, :create]
  match '/signin', to: 'sessions#new'

   root :to => 'sessions#new'

end

table_tennis/app/models/match.rb
class Match < ActiveRecord::Base
  attr_accessible :mDate, :player1, :player2, :state, :winner
end

table_tennis/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :points
  validates :name,  presence: true
  validates :password,  presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  
  def self.authenticate(user_info)
      find_by_email_and_password(user_info[:email],
                      user_info[:password])
  end

  def  add_point     
	self.points += 50
	self.save
  end

  def self.get_user(u_id)
    find_by_id(u_id)
  end

end

table_tennis/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

table_tennis/app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  layout 'main'
  
  def index
    @matches = Match.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end


  def show
    @match = Match.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end


  def new
    
    @match = Match.new
    @user = User.find(session[:current_user_id])
    @match.player1 = @user.id
    @match.player2 = User.find(params[:id]).id
    @match.mDate = Date.today 
    if @match.save
      flash.now[:success] = "You have successfully challenged one person!"
    end

  end

  def challenge
    @matches = Match.where(" player2 = ? AND state IS ?", session[:current_user_id] ,nil)
    respond_to do |format|
      format.html 
    end
  end

  def decision
    @match = Match.find(params[:mid])
    if params[:commit]=="Accept"
      flash.keep[:success] = "You have successfully accepted one challenge"
      @match.update_attributes(state: "pending")
      redirect_to :controller => :matches, :action=> 'challenge'
    end

    if params[:commit]=="Refuse"
      flash.keep[:success] = "You have successfully refused one challenge"
      @match.destroy
      redirect_to :controller => :matches, :action=> 'challenge'
    end


  end

  def result
    @matches = Match.where(" player1 = ? AND state = 'pending' AND mDate <= ?",session[:current_user_id],Date.today)
    respond_to do |format|
      format.html 
    end
	end

  def edit
    @match = Match.find(params[:id])
    session[:return_to] ||= request.referer

  end

  def update
    @match = Match.find(params[:id])
    respond_to do |format|
      if @match.update_attributes(params[:match])
      @match.update_attributes(state: "Finished")
      flash.keep[:success] = "One match has been successfully updated"
      @user = User.find(@match.winner)
      @user.add_point
        format.html { redirect_to session[:return_to] }
      else
        format.html { render action: "edit" }
     
      end
    end
  end


  def create
    @match = Match.new(params[:match])
  end

  def history

    @matches = Match.where(" (player1 = ? or player2 = ? )AND state = 'Finished'",session[:current_user_id],session[:current_user_id]).order("mDate ASC")
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
  end
end

table_tennis/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
 user= User.authenticate(params[:session])
 if user 
 	session[:current_user_id] = user.id
   redirect_to user
 else
 	flash[:error] = "Authentication Failed, please try again"
   render 'new'
 end
   
end

def destroy
	session[:current_user_id] = nil
	redirect_to root_url, :success => "Logged out!"

end

end

table_tennis/app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'main'
  
  def index
    @users = User.where(" id != ? ", 0 ).order("points DESC")
    @match = Match.new

    respond_to do |format|
      format.html # index.html.erb
    end
  end


  def show
    @user = User.find(session[:current_user_id])

    respond_to do |format|
      format.html # show.html.erb
      
    end
  end


  def new
    @user = User.new

    respond_to do |format|
      format.html 
      
    end
  end


  def edit
    @user = User.find(params[:id])
  end

 
  def create
    @user = User.new(params[:user])

    if @user.save
      session[:current_user_id] = @user.id
      user= User.find(@user.id)
      redirect_to user
    else
      flash[:error] = "Invalid credentials"
      redirect_to :back

    end
  end


  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end


  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
    end
  end
end

table_tennis/app/helpers/application_helper.rb
module ApplicationHelper
end

table_tennis/app/helpers/matches_helper.rb
module MatchesHelper
end

table_tennis/app/helpers/sessions_helper.rb
module SessionsHelper
end

table_tennis/app/helpers/users_helper.rb
module UsersHelper
end

table_tennis/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TableTennis</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:error] %>
      <div class="alert alert-error"><%= flash[:error] %></div>
<% end %>
<%= yield %>

</body>
</html>

table_tennis/app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Table Tennis Club</title>
		<%= stylesheet_link_tag "application", :media => "all"  %>
	</head>
	<body>
		<div id="container" >
			<div class="page-header">
				<h1>Table Tennis Club
					<small>Enjoy yourself</small>
				</h1>
			</div>
			<div id = "main">
				<div class="navbar">
					<div class="navbar-inner">
						
						<ul class="nav">
							<li class="divider-vertical"></li>
							<li><%= link_to "Home", user_path(session[:current_user_id])%></li>
								<li class="divider-vertical"></li>
								<li class="divider-vertical"></li>
							
							<li><%= link_to "Rank", :controller => :users, :action => 'index'%></li>
							<li class="divider-vertical"></li>
							<li class="divider-vertical"></li>
							
							<li><%= link_to "Challenges", :controller => :matches, :action=> 'challenge'%></li>
							<li class="divider-vertical"></li>
							<li class="divider-vertical"></li>
							
							<li><%= link_to "Results",:controller => :matches, :action=> 'result'%></li>
							<li class="divider-vertical"></li>
							<li class="divider-vertical"></li>
							
							<li><%= link_to "Statistics",:controller => :matches, :action=> 'history'%></li>
							<li class="divider-vertical"></li>
							<li class="divider-vertical"></li>
							<%= link_to "Logout", log_out_path, :class => "logoutclass"%>
								
						</ul>
					</div>
				</div>
				<div id="center">
					<div id="message">
					<% if flash[:success] %>
						<div class="alert alert-success">
							<%= flash[:success] %>
						</div>
						<% end %>
					</div>
				<div id="cenDoc">					
						<%= yield :cenDoc%>
					</div>
				</div>
				</div>
			<div id="footer">©2013 DIT</div> 
		</div>
	</div>
</body>
</html>

table_tennis/app/views/matches/challenge.html.erb
<% content_for :cenDoc do %>
<h1>Challenges you have received</h1>

<table class="table">
   <% if @matches.count == 0 %>
    <h4><%=  "Notice: You have no challenges "%></h4>
    <% else %>
  <tr>
    <th>Challenger</th>
    <th>Email</th>
    <th>Date</th>
    <th></th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <% @user = User.get_user(match.player1) %>
    <td><%= @user.name %></td>
    <td><%= @user.email %></td>
    <td><%= match.mDate %></td>
    <td><%= link_to "Accept", {:controller => 'matches', :action => 'decision', :mid => match, :commit => "Accept"}, :class =>"btn btn-primary"%></td>
    <td><%= link_to "Refuse", {:controller => 'matches', :action => 'decision', :mid => match, :commit => "Refuse"}, :class =>"btn btn-primary"%></td>
  </tr>
<% end %>
<tr>

</tr>
<% end %>
</table>

<% end %>

table_tennis/app/views/matches/decision.html.erb
<% content_for :cenDoc do %>
<h1>Your decision</h1>
<p>Once you choose one, you cannot make any change</p>
<table class="table ">

<%= form_for :match, :url => { :action => "decision" }, :html => { :method => 'put' }  do |f| %>
<tr>
    <th><%= submit_tag "Accept", class: "btn btn-primary"%></th>
    <th><%= submit_tag "Refuse", class: "btn btn-primary"%></th>
<% end %>
</tr>

</table>
<% end %>

table_tennis/app/views/matches/edit.html.erb
<% content_for :cenDoc do %>
<h1>Editing match</h1>
<p>Result:</p>
<%= form_for(@match) do |f| %>
<%= f.radio_button(:winner, @match.player1, :checked=> true) %>Win
<%= f.radio_button(:winner, @match.player2) %>Lose 
<%= f.submit "Update",class: "btn btn-primary"%>
<% end %>
<% end %>

table_tennis/app/views/matches/history.html.erb
<% content_for :cenDoc do %>
<% @u = User.find(session[:current_user_id])%>

<h1>Matches History</h1>
<% if @matches.count == 0 %>
    <h4><%=  "Notice: You have no matches finished "%></h4>
    <% else %>
<table class="table">
  
  <tr>
    <th>Challenger</th>
    <th>Oponent</th>
    <th>Match date</th>
    <th>State</th>
    <th>WinnerID</th> 
    <th>WinnerName</th> 
  </tr>

<% @matches.each do |match| %>
  <tr>
    <% @user = User.get_user(match.player1) %>
    <td><%= @user.name %></td>
    <% @user = User.get_user(match.player2) %>
    <td><%= @user.name %></td>
    <td><%= match.mDate %></td>
    <td><%= match.state %></td>
    <td><%= match.winner %></td>
    <% @user = User.get_user(match.winner) %>
    <td><%= @user.name %></td>
  </tr> 
<% end %>
</table>

<body onload="draw()">
  <tr><h3>Progress Chart<h3></tr>
  <tr>
    <canvas id="graph" width="470" height="220" style="border:1px solid #000000"></canvas> 
  </tr>
</body>
<script type="application/javascript">

    var matchCount = <%= @matches.count%>;
    var userId = <%= @u.id %>
    //document.write("userId = "+ userId);
    var xPath;
    var userPoints = new Array();
    var user;
    var pointsTot=0;
    
   // document.write("</br>Mach count= "+ matchCount);
   // document.write(", UserId: "+ userId);
    
    //assign points to current user
    for(var i=2; i<matchCount+2; i++){
        xPath = 'number(.//*/table[1]/tbody/tr['+i+']/td[5])';
        //document.write("</br>" + 'xPath:' + xPath);
        user = document.evaluate( xPath, document, null, XPathResult.ANY_TYPE, null);
        //document.write("user= " + user.numberValue + "</br>");
        if(user.numberValue == userId){
            userPoints.push(50);
        }
        else{
            userPoints.push(0);
        }
    }
    
    //print out points
    //for(var i=0; i<userPoints.length; i++){
    //    document.write("</br>" + 'userPoins:' + userPoints[i]);
    //}
    
    //totalPoint
    for(var i=0; i<userPoints.length; i++){
      pointsTot=pointsTot+userPoints[i];
    }
    //pointsTot=pointsTot+100;
    //document.write("</br>" + "Points total:" + pointsTot);
    
    //==================Start of graphics======================
    function draw(){
     var c=document.getElementById("graph");
      var pen=c.getContext("2d");
      var pen=c.getContext("2d")
      pen.beginPath();
    
      var colDist = 450/matchCount;
      var rowDist = 200/(pointsTot/50);
    
    //======================== Grid ===========================
      //Vertical grid
      pen.strokeStyle = '#00cc00';
      pen.lineWidth = 1;
    
      for(var i=1; i<matchCount; i++){
       pen.moveTo(20+i*colDist, 200);
        pen.lineTo(20+i*colDist,0);
        pen.stroke();
      }
    
     //Horizontal grid
      pen.lineWidth = 1;
      for(var i=1; i<pointsTot/50; i++){
        pen.moveTo(470, i*rowDist);
        pen.lineTo(20,i*rowDist);
        pen.stroke();
      }
    
      //Vertical base
      pen.beginPath();
      pen.moveTo(20,200);
      pen.strokeStyle = '#000000';
      pen.lineWidth = 1;
      pen.lineTo(20,0);
      pen.stroke();
    
      //Horizontal base
      pen.beginPath();
      pen.moveTo(20,200);
      pen.strokeStyle = '#000000';
      pen.lineWidth = 1;
      pen.lineTo(470,200);
      pen.stroke();
    //======================= Labels ==========================
     var c =document.getElementById("graph");
     var label = c.getContext("2d");
     var labelText=100;
      
      label.font="11px Arial";
    
      //points
      for(var i=0; i<pointsTot/50; i++){
        label.fillText(100+i*50, 0,202-i*rowDist);
      }
      label.rotate(-Math.PI/2);
      label.font="13px Arial";
      label.fillText("Points", -120,35);
      
      //games played
      label.font="11px Arial";
      label.rotate(Math.PI/2);
      for(var i=0; i<matchCount; i++){
        //label.fillText(i, i*colsDist-4,195);
        label.fillText(i, 20+i*colDist-2,215);
      }
      label.font="13px Arial";
      label.fillText("Games played", 210,195);
    //======================= Graph ==========================
      pen.beginPath();
      pen.moveTo(20,200);
      pen.strokeStyle = 'blue';
      pen.lineWidth = 5;
      var pointCounter=0;
      for(var i=0; i<matchCount; i++){
       pointCounter = pointCounter + userPoints[i];
       pen.lineTo(20+(i+1)*colDist,200 - pointCounter*(200/pointsTot));
       pen.stroke();
      }
    }
  </script>
  <% end %>
<% end %>

table_tennis/app/views/matches/new.html.erb
<% content_for :cenDoc do %>
<h1>Good Luck!</h1>
<%= link_to "Back", class: "btn btn-primary", :controller => :users, :action => 'index'%>
<% end %>

table_tennis/app/views/matches/result.html.erb
<% content_for :cenDoc do %>
<h1>Matches with pending result</h1>

<table class="table">
  <% if @matches.count == 0 %>
    <h4><%=  "Notice: You have no pending matches "%></h4>
    <% else %>
  <tr>
    <th>Challenger</th>
    <th>Oponent</th>
    <th>Date</th>
    <th>State</th>
    <th>Winner</th>
    <th></th>
  </tr>

<% @matches.each do |match| %>
  <tr>
    <% @user = User.get_user(match.player1) %>
    <td><%= @user.name %></td>
    <% @user = User.get_user(match.player2) %>
    <td><%= @user.name %></td>
    <td><%= match.mDate %></td>
    <td><%= match.state %></td>
    <td><%= match.winner %></td>
    <td><%= link_to 'Edit', edit_match_path(match) %></td>
  </tr>
<% end %>
<tr>

</tr>
<% end %>
</table>

<% end %>

table_tennis/app/views/users/index.html.erb
<% content_for :cenDoc do %>
<h1>All players</h1>
<% count = 0%>
<table class="table table-hover">
  <tr>
    <th>Rank</th>
    <th>Name</th>
    <th>Points</th>
    <th></th>
  </tr>

<% @users.each do |user| %>
<% if user.id != session[:current_user_id] %>
  <tr>
    <td><%= count +1 %></td> 
    <%count = count +1 %>
    <td><%= user.name %></td>
    <td><%= user.points %></td>
    
    <td><%= link_to 'Challenge', :controller => 'matches', :action => 'new', :id=>user %></td>
  </tr>
<% else %>
<tr id="tr_id">
    <td><%= count +1 %></td> 
    <%count = count +1 %>
    <td><%= user.name %></td>
    <td><%= user.points %></td>
    <td><b><%= "You are here"%></b></td>
  </tr>
    
<% end %>
  </tr>
<% end %>
</table>

<%end%>

table_tennis/app/views/users/show.html.erb
<% content_for :cenDoc do %>
<h1><b><%= @user.name %>, Welcome to our club</b></h1>
<p><b>Current Points:</b></p>
<h2><%= @user.points %></h2>
<p><i>Any questions? Please contact us.</i></p>
<%end%>